### ISSUE TITLE
Hello! It is recommended to increase the video preview function. Thanks!

### ISSUE THREAD

**Issue by zhouxinghong** [mjbvz/vscode-markdown-mermaid#181] opened 2023-03-02 11:31 UTC
Hello! It is recommended to increase the video preview function. Thanks!

**Comment by mjbvz** [comment] 2023-03-02 16:54
Please share an example

**Comment by mjbvz** [comment] 2023-03-06 21:36
Closing as unclear what the issue is

**Closed by mjbvz** 2023-03-06 21:36 UTC
