### ISSUE TITLE
Syntax error in graph mermaid version 9.1.1

### ISSUE THREAD

**Issue by heberhenrique** [mjbvz/vscode-markdown-mermaid#133] opened 2022-05-31 00:47 UTC
After update to latest version (1.14.0) preview is returning this message but nothing in my code was changed.

**Comment by heberhenrique** [comment] 2022-05-31 19:03
I will write without mermaid notation for markdown and with it to be more clear. So I have

```
sequenceDiagram
    autonumber
    Alice->>John: Ola John, como você está?
    loop Verificando Saúde
        John->>John: Luta contra hipocondria
    end
    Note right of John: pensamentos racionais!
    John-->>Alice: Estou bem!
    John->>Bob: E você bob?
    Bob-->>John: Muito bem!
```

**Then it will be this**:

```mermaid
sequenceDiagram
    autonumber
    Alice->>John: Ola John, como você está?
    loop Verificando Saúde
        John->>John: Luta contra hipocondria
    end
    Note right of John: pensamentos racionais!
    John-->>Alice: Estou bem!
    John->>Bob: E você bob?
    Bob-->>John: Muito bem!
```

But when I opened in preview tab of visual studio code message was in place of diagram.

**Comment by Cayan** [comment] 2022-06-20 14:55
I see a similar error on this example:
```
gitGraph
    commit id: "ZERO"
    branch develop
    commit id:"A"
    checkout main
    commit id:"ONE"
    checkout develop
    commit id:"B"
    checkout main
    commit id: "TWO"
    cherry-pick id:"A"
    commit id: "THREE"
    checkout develop
    commit id:"C"
```

**Comment by k-pypin** [comment] 2022-06-22 03:22
> I see a similar error on this example:
> 
> ```
> gitGraph
>     commit id: "ZERO"
>     branch develop
>     commit id:"A"
>     checkout main
>     commit id:"ONE"
>     checkout develop
>     commit id:"B"
>     checkout main
>     commit id: "TWO"
>     cherry-pick id:"A"
>     commit id: "THREE"
>     checkout develop
>     commit id:"C"
> ```

Cherry-pick support is added in Mermaid 9.1.2.
Currently this extension supports only 9.1.1.

**Comment by mjbvz** [comment] 2022-12-06 02:37
Closing this as I can't reproduce it. I suspect it was fixed already

**Closed by mjbvz** 2022-12-06 02:37 UTC
