### ISSUE TITLE
links not working

### ISSUE THREAD

**Issue by MrBjorn** [mjbvz/vscode-markdown-mermaid#252] opened 2024-03-28 09:43 UTC
I cant get the links working, bug? Its popup-menus. The syntax is:

::: mermaid
sequenceDiagram
    participant A
    links A: label @ url
:::

**Comment by mjbvz** [comment] 2024-03-28 19:14
What isn't working? Seems to match mermaid.live:

![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/6f41c6b9-c009-49c5-aba1-bcbb7400c3d7)

**Comment by mjbvz** [comment] 2024-04-30 22:12
Closing as unclear what the issue is

**Closed by mjbvz** 2024-04-30 22:12 UTC
