### ISSUE TITLE
Autoscrolling

### ISSUE THREAD

**Issue by wflouw** [mjbvz/vscode-markdown-mermaid#71] opened 2020-07-24 10:10 UTC
Hi, have used the VSCode Plug-in for a while to preview Mermaid diagrams and it worked fine. Recently (after vscode update) I noticed some strange scrolling phenomena. When I type (in a single line) both the Markdown-preview and readme.md editor-tabs auto-scroll up and down in an unpredictable manner.

**Comment by pauloneves** [comment] 2020-08-25 23:26
Same problem here. My workaround is to temporarily move the diagram to the top of the file.

**Comment by HanKruiger** [comment] 2020-10-23 10:04
Some additional information:

I tried to work around this by disabling sync (both ways) altogether:

```json
"markdown.preview.scrollPreviewWithEditor": false,
"markdown.preview.scrollEditorWithPreview": false,
```

But the problem (at least partly) persists. The editor view doesn't scroll anymore, but the preview does (it always scrolls down).

**Comment by kingsimba** [comment] 2021-02-20 12:32
Same problem +1.  But your workaround is not helpful when you have multiple mermaid diagram in the same file.

> Same problem here. My workaround is to temporarily move the diagram to the top of the file.

**Comment by yeders** [comment] 2021-03-10 13:23
I too am experiencing this, but mine scrolls to the bottom every time. It's quite annoying when the diagram I am working on is the top one 👎

**Comment by stefandeml** [comment] 2021-05-18 10:29
yeah ... only option I see for now is to temporarily disable the extension during editing and only use it for preview / review.

**Comment by gimbo** [comment] 2021-06-02 17:05
I'm experiencing this (or something like it) too; for me, editing above the diagram is fine but any edits I make below the diagram cause the editor and preview to both scroll up a few lines (in a distracting and jumpy way) — so for me moving the diagram to the top would make the problem _worse_, and I need to move it to the bottom or (better, yes) disable the plugin while working on the document.

Demo video (silent): https://youtu.be/YOxVFjRMISo — any vertical movement before the 44 second mark is me scrolling the page, but after that it's just the crazy jumping happening on its own.

This is with a fresh install of VSCode, and all extensions disabled except this one, on a Mac running Big Sur (details below).

---

### Versions

MacOS Big Sur 11.3.1 (20E241)

VSCode (fresh install today to check this):

Version: 1.56.2 (Universal)
Commit: 054a9295330880ed74ceaedda236253b4f39a335
Date: 2021-05-12T17:44:30.902Z
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.4.0

Markdown Preview Mermaid Support version: v1.9.2

All other extensions disabled.

**Comment by pearj** [comment] 2021-07-14 23:44
I've spent quite a while investigating this, and I found out a few things.

It jumps all over the place because the preview renders the code of the mermaid diagram first, and then quickly afterwards replaces it with the actual diagram.

I tried to using the [mermaid API](https://mermaid-js.github.io/mermaid/#/usage?id=api-usage) on the extension side (`index.js`), however the extension runs in NodeJS, and [mermaid-js doesn't work in NodeJS](https://github.com/mermaid-js/mermaid/issues/1183). So I then tried using [localStorage on the webview](https://github.com/pearj/vscode-markdown-mermaid/blob/48f517cd4d06d7739056aa9d583f81e753f9a0c3/page.js#L13-L38) side to save the height of the rendered diagram and reapply it before trying to render the diagram. However, it's too late to add the previous height by the time the script runs (the script runs in async mode), and it doesn't help, so I tried adding a [script in the generated html](https://github.com/pearj/vscode-markdown-mermaid/blob/48f517cd4d06d7739056aa9d583f81e753f9a0c3/index.js#L51) directly, but the script got blocked.

I tried putting a fixed height like this `<div styles="min-height:30em" class="${pluginKeyword}">`, and that does fix the problem for diagrams that are smaller than `30em`, but obviously make the diagrams that high, which is not really a solution but does prove what the issue is.

Basically we need a way for the webview to communicate with extension to let it know what the sizes of the mermaid diagrams are. It seems like [Microsoft has gone out of it's way to stop this](https://code.visualstudio.com/api/extension-capabilities/overview#no-dom-access) sort of thing. But I think if we embedded a http server inside the extension, then this would probably work, although it seem a bit kludgy solution.  But I can't think of another way to enable this communication, but I haven't written VSCode extensions before.
I did discover that inside the webview you can find name of the markdown file by looking in the base element (`document.querySelector("base").href`).
So that means if there was a webserver you could send the name of the file as well as the size of the diagrams, in-case you have multiple windows open.
Running a webserver inside the extension would probably be a little bit fiddly, especially in the remote scenario like WSL or SSH, as it might not be easy to guarantee that the http server is always accessible.

@mjbvz is there a supported way to allow posting messages from the webview back to the extension. I can see at the top of the markdown preview webview there is a script for the vscodeApi that can post messages, although it removes to access to the VSCode API as soon as it runs. I think if we could specify that certain scripts can run without async, that would also help too.

**Comment by xmedeko** [comment] 2021-11-10 13:34
Workaround by disabling scrolling mentioned above works for me, but is not convenient. 

What about some workarounds:
* Specify expected height of he image in the mermaid comment, e.g. `%% vscode: min-height:30em`, the extension would pick it and use as `style` as mentioned in the previous post https://github.com/mjbvz/vscode-markdown-mermaid/issues/71#issuecomment-880281337
* Make some markdown / mermaid code cache and update the final image when the mermaid code of the image is changed only.
* User settings: to auto refresh images less frequently, e.g. every 2 sec only.
* User settings: to disable auto refresh (per user setting) completely, do it on a certain VS Code command (F1) only. 
* User settings: refresh the final image on the click on the image only (do not now if it's possible).

**Comment by mjbvz** [comment] 2022-12-07 19:57
If you are still seeing this issue, can you please share an example markdown file and steps to reproduce the problem so I can take a look

**Comment by xmedeko** [comment] 2022-12-08 08:08
@mjbvz 👍  The problem does not appear for me now, VS Code 1.73.1, Markdown Preview Mermaid Support 1.16.0.

**Comment by mjbvz** [comment] 2022-12-08 17:14
Ok tentatively closing but please share the markdown document text if this still isn't working in some cases

**Closed by mjbvz** 2022-12-08 17:14 UTC
Labels: help wanted, info-needed

**Comment by pearj** [comment] 2022-12-15 04:25
I couldn't reproduce it either anymore hooray. I guess vscode must have changed the webview behaviour.

**Comment by JohnLudlow** [comment] 2023-09-07 11:49
Hi,

I can reproduce the issue with this markdown (also see the [attached video](https://github.com/mjbvz/vscode-markdown-mermaid/assets/1769289/2745c326-a976-4b97-a1c7-642ce23aec6e)):

    # This is a test of mermaid and markdown

    These are some ideas

    1. Drink coffee
    2. ???
    3. CONQUER THE WORLD!!!

    ## A mermaid diagram:

    ```mermaid
    sequenceDiagram
        participant yaml as CI YAML
        participant pwsh as PowerShell Scripts
        participant proj as .NET Project

        activate yaml
            yaml  -->>  yaml  : GIT FETCH
            yaml  -->>  yaml  : VERSION FROM PIPELINE COUNTER

            Note over yaml, pwsh: INIT
            yaml  ->>+  pwsh  : SET ENVIRONMENT VARIABLES
            pwsh  -->>- yaml  : 

            rect rgb(254, 255, 173)
            Note over yaml, proj: BUILD
            yaml  ->>+  proj  : DOTNET RESTORE
            proj  -->>- yaml  : 

            yaml  ->>+  proj  : DOTNET BUILD
            proj  -->>- yaml  : 
            
            yaml  ->>+  proj  : DOTNET TEST
            proj  -->>- yaml  : 
            end

            rect rgb(254, 255, 173)
            Note over yaml, proj: PACK / PUBLISH
            yaml  ->>+  proj  : DOTNET PACK
            proj  -->>- yaml  : 

            yaml  ->>+  proj  : DOTNET PUBLISH
            proj  -->>- yaml  : 

            yaml  -->>  yaml  : PUBLISH ARTIFACTS
            end
        deactivate yaml
    ```

    A chart

    ```mermaid
    sequenceDiagram
        participant yaml as CI YAML
        participant pwsh as PowerShell Scripts

        activate yaml
            yaml  -->>  yaml  : GIT FETCH
            yaml  -->>  yaml  : RESOURCE FETCH
            yaml  -->>  yaml  : ARTIFACT FETCH

            yaml  ->>   pwsh  : SET ENVIRONMENT VARIABLES
            pwsh  -->>  yaml  : 
        deactivate yaml
    ```

    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam ac lorem non turpis interdum aliquam. Sed 
    tempor aliquet dui, at luctus turpis rutrum in. Nullam at nibh placerat, varius mi ac, varius sapien. In 
    nec facilisis dui. Vestibulum dignissim lacus in massa tristique, vel mattis nisi aliquam. Nunc vel semper 
    sem. Suspendisse lobortis consectetur eleifend. Phasellus ornare augue odio, sed iaculis justo luctus 
    quis. Phasellus ligula velit, vestibulum id nisl in, imperdiet faucibus dui. Donec ligula magna, volutpat 
    non urna in, pulvinar rhoncus nibh. Sed semper nulla at ex aliquet malesuada. Cras ornare nunc ut 
    condimentum facilisis. Nam dignissim metus diam, eu bibendum eros porttitor sit amet. Fusce vehicula 
    dictum nisl, ac euismod orci hendrerit in. Etiam fermentum a nibh in maximus. Duis tristique a leo quis 
    convallis.

    Aliquam erat volutpat. Mauris magna urna, convallis non orci sed, mattis varius lorem. Nulla malesuada 
    enim mi, vitae vehicula leo fermentum non. Ut ac volutpat dui. Phasellus consectetur a felis sed lobortis. 
    Integer turpis urna, molestie fermentum sollicitudin a, elementum vitae augue. Donec molestie quam vitae 
    augue pretium euismod. Vivamus sapien nisi, volutpat fermentum leo vel, tincidunt aliquet diam. Nunc 
    egestas nibh enim. Sed sit amet tempor orci, et consequat metus.
