### ISSUE TITLE
stateDiagram is not rendered

### ISSUE THREAD

**Issue by IvanKostyuk** [mjbvz/vscode-markdown-mermaid#235] opened 2024-01-20 20:11 UTC
no problem with flowchart and sequence, but state diagram is not rendered.

**Comment by mjbvz** [comment] 2024-01-20 20:47
Please share an example

**Comment by RokeJulianLockhart** [comment] 2024-02-03 13:15
> https://github.com/mjbvz/vscode-markdown-mermaid/issues/235#issue-2092225477

@IvanKostyuk, https://mermaid.js.org/syntax/stateDiagram.html#state-diagrams as:

```.MD
::: mermaid
stateDiagram-v2
    [*] --> Still
    Still --> [*]

    Still --> Moving
    Moving --> Still
    Moving --> Crash
    Crash --> [*]

:::
```

...works for me.

**Comment by mshalaby** [comment] 2024-02-19 19:27
> no problem with flowchart and sequence, but state diagram is not rendered.

@IvanKostyuk in case this issue is still relevant, I can confirm the state diagram works for me. However, a possible cause that I've noticed, is that when a mermaid diagram fails to render for any reason (such as: an unsupported diagram or a syntax error), it causes all subsequent diagrams within the markdown file not to render. So, the issue might actually be with the preceding diagram rather than with the state diagram itself. Hope that helps!

**Comment by mjbvz** [comment] 2024-03-28 19:17
Works for me too

![Image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/12821956/7273d971-f9e4-4d4e-8bfe-9d0c6fb288bb)


Closing as not-reproducible without more info

**Closed by mjbvz** 2024-03-28 19:17 UTC
Labels: info-needed

**Comment by hirakuro** [comment] 2025-10-15 09:31
Hi.

I faced same problem when both of "vscode-markdown-mermaid" and "vscode-mermaid-preview" are installed.
- https://marketplace.visualstudio.com/items?itemName=vstirbu.vscode-mermaid-preview

And I solved this with uninstalling one of them, it doesn't matter which one.
