### ISSUE TITLE
Diagram is too big

### ISSUE THREAD

**Issue by pengyuwei** [mjbvz/vscode-markdown-mermaid#80] opened 2020-10-05 10:30 UTC
Having started using mermaid, recently feels very good and it works well, but for me the diagram is a bit too big.
Most of the time we just need a small diagram (maybe 1/4 of the current size is enough) . Hope to provide a way to zoom the diagram to change occupy screen space.

``` mermaid
graph TD
    subgraph Research
    A(Test two var)-->B(test variables by statistical method))
    B-->C(correlation coefficient)
    end
```

**Comment by stevenzlee** [comment] 2021-03-06 03:26
My current work around is to control graph size with markdown css. The selector is `div.mermaid > svg`.

However, I tried setting `width:50%` and it changes all graph sizes to the same width, which makes no sense because I have mixed large and small graphs and wish to adjust according to the embedded svg width. 

Then I tried using `transform:scale(0.5); transform-origin: top left;` instead, and that properly shrinks embedded svg and moves it to the top, but does not change its container frame, and leaves large amount of empty spacing.

Still looking for a solution - any suggestion is appreciated.

**Comment by jan9won** [comment] 2021-12-21 10:00
Another temporary solution.
_(in case your graph's direction is `LR`)_

Add style block below, inside the markdown document itself (or to the custom css file).

1. You will get scrollable container.
2. You can change `div.mermaid > svg > width` as `rem` to zoom in and out consistently, regardless of preview window size.

```html
<style>
div.mermaid {
	overflow-x: scroll;
	background: rgb(15, 15, 15);
}
div.mermaid > svg {
	width: 100rem; /* EDIT HERE */
	height: 50%;
	padding: 1em;
}
</style>
```

**Comment by mjbvz** [comment] 2022-12-06 18:31
Duplicate of #125

**Closed by mjbvz** 2022-12-06 18:31 UTC
