### ISSUE TITLE
::: isn't the same as ``` ?

### ISSUE THREAD

**Issue by o-o00o-o** [mjbvz/vscode-markdown-mermaid#82] opened 2020-10-07 19:42 UTC
For the exact same diagram I get an error if I use ::: but not if I use ```. Doesn't seem likely but true!

This works. Switch the ``` for ::: and it doesn't.

``` mermaid
graph TB

    SDS(Data Sources)
    Users((Users))
    ExtProc(External Processes)
    MDS[MDS]

    ExtProc --> SDS    
    Users --> SDS
    Users --"Tables where Users are owner"--> MDS

    subgraph SSIS
        EtlPreE(Etl Pre Extract) -.-> EtlE
        EtlE(Etl Extract) -.-> EtlPreL
        EtlPreL(Etl Pre Load) -.-> EtlL
        EtlL(Etl Load) -.-> EtlPstL
        EtlPstL(Etl Post Load)
    end

    subgraph DW
        DWS[Dw Staging]
        DWK[Dw Star Schema]

        EtlE --> DWS
        EtlPreL -- bad etls that don't extract--> DWK
        EtlL --> DWK
        DWS -.-> DWK
    end

    subgraph Deploy
        SSDTPD(Post Deploy)
    end

    SSDTPD --"Tables where System is owner (static)"--> MDS
    SDS --> EtlE
    SDS --> EtlPreE
    EtlPreE --"Tables where MDS is Data Integrator for Data Stewards"--> MDS
    MDS --> EtlE
    EtlPstL --"Tables where DW is owner (dynamic)"--> MDS
```

**Comment by mjbvz** [comment] 2020-11-20 07:44
Seems like a duplicate of #83

**Closed by mjbvz** 2020-11-20 07:44 UTC
