### ISSUE TITLE
Could you help to upgrade to mermaid to support mindmaps feature please?

### ISSUE THREAD

**Issue by jay-zhou-yan** [mjbvz/vscode-markdown-mermaid#159] opened 2022-12-06 02:30 UTC
Hi

Thank you very much for this excellent extension! Thanks again.

When I use the syntax of Mindmap, it always report errors and cannot preview correctly. Is it possible to help upgrade to the version of mermaid that supports Mindmap feature? Thank you very much!

**Comment by mjbvz** [comment] 2022-12-06 02:34
Duplicate of #153

**Closed by mjbvz** 2022-12-06 02:34 UTC
