### ISSUE TITLE
integrate mermaind diagrams in jupiter notebooks (Visual Studio Code)

### ISSUE THREAD

**Issue by ITCTOM** [mjbvz/vscode-markdown-mermaid#158] opened 2022-12-05 11:24 UTC
Is it possible to integrate mermaind Diagrams als "Markdown Cells" to jupiter Notebooks using .net Interactive?

**Comment by ITCTOM** [comment] 2022-12-05 11:45
now it´s working using "Polyglot Notebooks" Plugin.

**Comment by mjbvz** [comment] 2022-12-06 02:37
Duplicate of #137

**Closed by mjbvz** 2022-12-06 02:37 UTC
