### ISSUE TITLE
✨ [Feature request] Zoom mermaid diagram like on Github

### ISSUE THREAD

**Issue by mlaidouni** [mjbvz/vscode-markdown-mermaid#259] opened 2024-05-26 21:23 UTC
Can you add this new feature: the possibility to "zoom" a diagram like on github ?

## Exemple
 
````
```mermaid
graph LR
    A --> B
    B --- C
    A --> D
    D --> E
```
`````

## Expected result

![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/151235313/0d5e6802-d5fb-4118-b5ad-f5e2f2a7b3a6)

A specially this:

![image](https://github.com/mjbvz/vscode-markdown-mermaid/assets/151235313/e14146c2-bd7d-49a9-9582-559b21f410d4)

**Comment by mjbvz** [comment] 2024-06-18 20:31
Duplicate of #125

**Closed by mjbvz** 2024-06-18 20:31 UTC
